# Generated by Django 3.2.20 on 2023-07-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='posts_viewcount',
            field=models.IntegerField(default=0),
        ),
    ]
