# Generated by Django 3.2.24 on 2024-06-27 03:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_mode_name', models.CharField(default='', max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(default='', max_length=140)),
                ('last_logged_in', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='RQAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='ServerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=140)),
                ('player_id', models.CharField(default='0', max_length=140)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='click_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.URLField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='price',
            name='location_of_product',
            field=models.CharField(default='Remote', max_length=200),
        ),
        migrations.AddField(
            model_name='price',
            name='product_type',
            field=models.CharField(choices=[('unspecified', 'Unspecified'), ('package_post', 'Posted Package'), ('package_courier', 'Courier Routes Package'), ('package_direct', 'Choose A Courier'), ('package_pick_up', 'Pick Up Yourself (with a pick-up)'), ('package_collect', 'Collect Yourself (by hand)'), ('link', 'Collect Links'), ('poem', 'Just Words'), ('tickets', 'Event Tickets'), ('classes', 'Classes'), ('class_material', 'Class Material'), ('other', 'Other Deal')], default='unspecified', max_length=200),
        ),
        migrations.CreateModel(
            name='TaxIncentive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.IntegerField(default=0)),
                ('bounty', models.IntegerField(default=0)),
                ('bounty_description', models.TextField(default='', max_length=14400)),
                ('initiators', models.ManyToManyField(default=None, related_name='initiators', to='Bable.Author')),
                ('passers', models.ManyToManyField(default=None, related_name='passers', to='Bable.Author')),
                ('voters', models.ManyToManyField(default=None, related_name='voters', to='Bable.Author')),
                ('words', models.ManyToManyField(default=None, to='Bable.Word')),
            ],
        ),
        migrations.CreateModel(
            name='ServerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(default='', max_length=140)),
                ('server_log_in_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('server_users', models.ManyToManyField(default=None, to='Bable.ServerUser')),
            ],
        ),
        migrations.CreateModel(
            name='RequestQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=140)),
                ('answers', models.ManyToManyField(default=None, to='Bable.RQAnswers')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('max_size_of_server', models.IntegerField(default=12)),
                ('current_log_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('players', models.ManyToManyField(default=None, to='Bable.Player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='server_history',
            field=models.ManyToManyField(default=None, to='Bable.ServerHistory'),
        ),
        migrations.CreateModel(
            name='MinecraftServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.FloatField(default=0)),
                ('domain', models.TextField(default='', max_length=140)),
                ('port', models.IntegerField(default=1234)),
                ('online', models.BooleanField(default=False)),
                ('location', models.CharField(default='', max_length=140)),
                ('registered_by', models.CharField(default='', max_length=140)),
                ('registered_since', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('about', models.TextField(default='', max_length=4000)),
                ('website', models.URLField(default='', max_length=400)),
                ('game_modes', models.ManyToManyField(default=None, to='Bable.GameMode')),
                ('player_count', models.ManyToManyField(default=None, to='Bable.PlayerCount')),
                ('sponsor', models.ManyToManyField(default=None, to='Bable.Sponsor')),
                ('tags', models.ManyToManyField(default=None, to='Bable.Word')),
                ('theme', models.ManyToManyField(default=None, to='Bable.SpaceSource')),
            ],
        ),
        migrations.AddField(
            model_name='anon',
            name='minecraft_servers',
            field=models.ManyToManyField(default=None, to='Bable.MinecraftServer'),
        ),
        migrations.AddField(
            model_name='availability',
            name='post_request_questions',
            field=models.ManyToManyField(default=None, related_name='post_request_questions', to='Bable.RequestQuestion'),
        ),
        migrations.AddField(
            model_name='availability',
            name='request_questions',
            field=models.ManyToManyField(default=None, related_name='request_questions', to='Bable.RequestQuestion'),
        ),
        migrations.AddField(
            model_name='space',
            name='minecraft_servers',
            field=models.ManyToManyField(default=None, to='Bable.MinecraftServer'),
        ),
        migrations.AddField(
            model_name='space',
            name='tax_incentives',
            field=models.ManyToManyField(default=None, to='Bable.TaxIncentive'),
        ),
    ]
