# Generated by Django 3.2.20 on 2023-08-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='anon_user_id',
            field=models.CharField(default='', max_length=256),
        ),
    ]
