# Generated by Django 4.0.2 on 2022-10-26 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votes',
            name='the_vote_style',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='name', to='Bable.spacesource'),
        ),
    ]
