# Generated by Django 3.2.20 on 2023-08-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anon',
            name='applied_dictionaries',
            field=models.ManyToManyField(default=None, related_name='applied_dictionaries', to='Bable.Dictionary_Source'),
        ),
    ]
