# Generated by Django 3.2.20 on 2023-08-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='sum_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='price',
            name='sum_invoices',
            field=models.IntegerField(default=0),
        ),
    ]
