# Generated by Django 4.2.6 on 2024-06-08 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userviews',
            name='previous_view_time_between_pages',
            field=models.DurationField(default=datetime.timedelta(seconds=1)),
        ),
    ]
