# Generated by Django 3.2.20 on 2023-08-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anon',
            name='stripe_api_secret',
            field=models.CharField(default='', max_length=600, null=True),
        ),
    ]
