# Generated by Django 3.2.20 on 2023-08-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anon',
            name='stripe_webhook_secret',
            field=models.CharField(default='', max_length=600),
        ),
    ]
