# Generated by Django 3.2.24 on 2024-06-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='comments',
            field=models.ManyToManyField(default=None, to='Bable.Comment_Source'),
        ),
    ]
