# Generated by Django 3.2.20 on 2023-08-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anon',
            name='received_messages',
            field=models.ManyToManyField(default=None, related_name='received_messages', to='Bable.Comment_Source'),
        ),
        migrations.AlterField(
            model_name='anon',
            name='sent_messages',
            field=models.ManyToManyField(default=None, related_name='sent_messages', to='Bable.Comment_Source'),
        ),
    ]
