# Generated by Django 3.2.24 on 2024-06-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AngelNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digits', models.IntegerField(default=1)),
                ('numbers', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=14400)),
                ('sponsors', models.ManyToManyField(default=None, to='Bable.Sponsor')),
            ],
        ),
        migrations.AddField(
            model_name='anon',
            name='angel_numbers',
            field=models.ManyToManyField(default=None, to='Bable.AngelNumber'),
        ),
        migrations.AddField(
            model_name='comment',
            name='angel_numbers',
            field=models.ManyToManyField(default=None, to='Bable.AngelNumber'),
        ),
        migrations.AddField(
            model_name='post',
            name='angel_numbers',
            field=models.ManyToManyField(default=None, to='Bable.AngelNumber'),
        ),
        migrations.AddField(
            model_name='space',
            name='angel_numbers',
            field=models.ManyToManyField(default=None, to='Bable.AngelNumber'),
        ),
    ]
