# Generated by Django 3.2.24 on 2024-06-27 03:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_mode_name', models.CharField(default='', max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(default='', max_length=140)),
                ('last_logged_in', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ServerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=140)),
                ('player_id', models.CharField(default='0', max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='ServerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(default='', max_length=140)),
                ('server_log_in_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('server_users', models.ManyToManyField(default=None, to='Bable.ServerUser')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('max_size_of_server', models.IntegerField(default=12)),
                ('current_log_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('players', models.ManyToManyField(default=None, to='Bable.Player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='server_history',
            field=models.ManyToManyField(default=None, to='Bable.ServerHistory'),
        ),
        migrations.CreateModel(
            name='MinecraftServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.FloatField(default=0)),
                ('domain', models.TextField(default='', max_length=140)),
                ('port', models.IntegerField(default=1234)),
                ('online', models.BooleanField(default=False)),
                ('location', models.CharField(default='', max_length=140)),
                ('registered_by', models.CharField(default='', max_length=140)),
                ('registered_since', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('about', models.TextField(default='', max_length=4000)),
                ('website', models.URLField(default='', max_length=400)),
                ('game_modes', models.ManyToManyField(default=None, to='Bable.GameMode')),
                ('player_count', models.ManyToManyField(default=None, to='Bable.PlayerCount')),
                ('sponsor', models.ManyToManyField(default=None, to='Bable.Sponsor')),
                ('tags', models.ManyToManyField(default=None, to='Bable.Word')),
                ('theme', models.ManyToManyField(default=None, to='Bable.SpaceSource')),
            ],
        ),
        migrations.AddField(
            model_name='anon',
            name='minecraft_servers',
            field=models.ManyToManyField(default=None, to='Bable.MinecraftServer'),
        ),
        migrations.AddField(
            model_name='space',
            name='minecraft_servers',
            field=models.ManyToManyField(default=None, to='Bable.MinecraftServer'),
        ),
    ]
