# Generated by Django 3.2.20 on 2023-08-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0002_auto_20230821_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='anon',
            name='stripe_api_key',
            field=models.CharField(default='', max_length=600, null=True),
        ),
    ]
