# Generated by Django 3.2.24 on 2024-06-21 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0002_space_storefronts'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='location_of_product',
            field=models.CharField(default='Remote', max_length=200),
        ),
        migrations.AddField(
            model_name='price',
            name='product_type',
            field=models.CharField(choices=[('unspecified', 'Unspecified'), ('package_post', 'Posted Package'), ('package_courier', 'Courier Routes Package'), ('package_direct', 'Choose A Courier'), ('package_pick_up', 'Pick Up Yourself (with a pick-up)'), ('package_collect', 'Collect Yourself (by hand)'), ('link', 'Collect Links'), ('poem', 'Just Words'), ('tickets', 'Event Tickets'), ('classes', 'Classes'), ('class_material', 'Class Material'), ('other', 'Other Deal')], default='unspecified', max_length=200),
        ),
        migrations.AddField(
            model_name='price',
            name='sponsors',
            field=models.ManyToManyField(default=None, to='Bable.Sponsor'),
        ),
    ]
