# Generated by Django 4.1.5 on 2023-06-17 04:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0002_alter_votes_the_vote_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='votes',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
