# Generated by Django 3.2.20 on 2023-07-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0002_space_posts_viewcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='anon',
            name='space_sort_char',
            field=models.CharField(choices=[('-viewcount', 'Most Viewed'), ('viewcount', 'Least Viewed'), ('-latest_change_date', 'Recent Change'), ('latest_change_date', 'Distant Change'), ('-posts_viewcount', 'Most Post Views'), ('posts_viewcount', 'Least Post Views'), ('-votes_count', 'Most Votes'), ('votes_count', 'Least Votes'), ('-sponsor_count', 'Most Sponsored'), ('sponsor_count', 'Least Sponsored'), ('-approved_voter_count', 'Most Approved Voters'), ('approved_voter_count', 'Least Approved Voters')], default='latest_change_date', max_length=180),
        ),
        migrations.AddField(
            model_name='space',
            name='approved_voter_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='space',
            name='postcount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='space',
            name='sponsor_count',
            field=models.IntegerField(default=0),
        ),
    ]
