# Generated by Django 3.2.24 on 2024-06-10 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0002_auto_20240610_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userviews',
            name='anon',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='Bable.anon'),
        ),
    ]
