# Generated by Django 3.2.20 on 2023-08-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0002_price_anon_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anon',
            name='anon_sort_char',
            field=models.CharField(choices=[('-sum_dictionaries', 'Most Dictionaries'), ('sum_dictionaries', 'Least Dictionaries'), ('-sum_purchased_dictionaries', 'Most Purchased Dictionaries'), ('sum_purchased_dictionaries', 'Least Purchased Dictionaries'), ('-sum_excluded_authors', 'Most Authors Blocked'), ('sum_excluded_authors', 'Least Authors Blocked'), ('-sum_examples', 'Most Examples'), ('sum_examlpes', 'Least Examples'), ('-sum_tasks', 'Most Tasks'), ('sum_tasks', 'Least Tasks'), ('-sum_posts', 'Most Posts'), ('sum_posts', 'Least Posts'), ('-sum_posted_comments', 'Most Posted Comments'), ('sum_posted_comments', 'Least Posted Comments'), ('-sum_saved_comments', 'Most Saved Comments'), ('sum_saved_comments', 'Least Saved Comments'), ('-sum_purchased_spaces', 'Most Purchased Spaces'), ('sum_purchased_spaces', 'Least Purchased Spaces'), ('-sum_created_votestyles', 'Most Created Votestyles'), ('sum_created_votestyles', 'Least Created Votestyles'), ('-latest_change_date', 'Most Recent Update'), ('latest_change_date', 'Least Recent Update'), ('-creation_date', 'Newest Account Creation'), ('creation_date', 'Oldest Account Creation')], default='latest_change_date', max_length=180),
        ),
    ]
