# Generated by Django 3.2.20 on 2023-08-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0002_remove_price_anon_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='anon_id',
            field=models.CharField(default='', max_length=256),
        ),
    ]
