# Generated by Django 3.2.24 on 2024-07-01 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0002_auto_20240630_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.FloatField(default=0)),
                ('words', models.TextField(default='I think this is Working', max_length=50)),
                ('author', models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='Bable.author')),
            ],
        ),
        migrations.AddField(
            model_name='angelnumber',
            name='attributions',
            field=models.ManyToManyField(default=None, to='Bable.Attribution'),
        ),
    ]
