# Generated by Django 3.2.24 on 2024-06-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0002_space_storefronts'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='sponsors',
            field=models.ManyToManyField(default=None, to='Bable.Sponsor'),
        ),
    ]
