# Generated by Django 4.2.6 on 2023-10-28 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0003_commentlocations_votings_searchurl_anon_search_urls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchurl',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Bable.author'),
        ),
    ]
