# Generated by Django 3.2.20 on 2023-08-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0003_alter_anon_anon_sort_char'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_posts_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='page_density',
            name='scroll_type',
            field=models.CharField(choices=[('-viewcount', 'Viral'), ('viewcount', 'Early'), ('-latest_change_date', 'Freshest'), ('latest_change_date', 'Eldest'), ('-sum_has_viewed', 'Uniques'), ('-sum_has_voted', 'Voters'), ('-sum_dictionaries', 'Broadness'), ('-sum_words', 'Intricacy'), ('-sum_comments', 'Talkative'), ('sum_comments', 'Silencio'), ('-under_talked', 'Under Commented'), ('under_talked', 'Over Commented'), ('-sum_spaces', 'Homes'), ('-sum_sponsors', 'Encouraged'), ('-votes_count', 'Votes'), ('votes_count', 'Unvoted'), ('-shuffle', 'Shuffle'), ('shuffle', 'Counter-Shuffle'), ('-attention', 'Attention Span Up'), ('attention', 'Scroll Past')], default='latest_change_date', max_length=180),
        ),
        migrations.AddField(
            model_name='post',
            name='attention',
            field=models.IntegerField(default=99999999),
        ),
        migrations.AddField(
            model_name='post',
            name='shuffle',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='anon',
            name='post_sort_char',
            field=models.CharField(choices=[('-viewcount', 'Viral'), ('viewcount', 'Early'), ('-latest_change_date', 'Freshest'), ('latest_change_date', 'Eldest'), ('-sum_has_viewed', 'Uniques'), ('-sum_has_voted', 'Voters'), ('-sum_dictionaries', 'Broadness'), ('-sum_words', 'Intricacy'), ('-sum_comments', 'Talkative'), ('sum_comments', 'Silencio'), ('-under_talked', 'Under Commented'), ('under_talked', 'Over Commented'), ('-sum_spaces', 'Homes'), ('-sum_sponsors', 'Encouraged'), ('-votes_count', 'Votes'), ('votes_count', 'Unvoted'), ('-shuffle', 'Shuffle'), ('shuffle', 'Counter-Shuffle'), ('-attention', 'Attention Span Up'), ('attention', 'Scroll Past')], default='latest_change_date', max_length=180),
        ),
        migrations.AddField(
            model_name='page_density',
            name='ids',
            field=models.ManyToManyField(default=None, to='Bable.Post_id'),
        ),
    ]
