# Generated by Django 3.2.24 on 2024-06-17 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0003_alter_userviews_anon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anon',
            name='storefronts',
        ),
        migrations.RemoveField(
            model_name='dictionary',
            name='storefronts',
        ),
        migrations.RemoveField(
            model_name='space',
            name='storefronts',
        ),
        migrations.DeleteModel(
            name='Storefront',
        ),
    ]
