# Generated by Django 3.2.20 on 2023-08-19 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0003_price_anon_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='anon_id',
        ),
    ]
