# Generated by Django 3.2.11 on 2023-01-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0003_auto_20221116_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anon',
            name='post_sort',
            field=models.IntegerField(choices=[(0, 'viral'), (1, 'early'), (2, 'freshest'), (3, 'eldest'), (11, 'votes'), (12, 'unvoted')], default=0),
        ),
    ]
