# Generated by Django 4.1.5 on 2023-06-17 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0003_votes_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='the_vote_name',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
