# Generated by Django 3.2.20 on 2023-07-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0003_auto_20230716_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='anon',
            name='dictionary_sort_char',
            field=models.IntegerField(choices=[('-latest_change_date', 'Most Recent Change'), ('latest_change_date', 'Least Recent Change'), ('-price', 'Most Expensive'), ('price', 'Least Expensive'), ('-creation_date', 'Oldest'), ('creation_date', 'Newest'), ('-traded_date', 'Most Recent Trade'), ('traded_date', 'Least Recent Trade'), ('-word_count', 'Most Words'), ('word_count', 'Least Words'), ('-votes_count', 'Most Votes'), ('votes_count', 'Least Votes'), ('-rendition_count', 'Most Renditions'), ('rendition_count', 'Least Renditions'), ('-analysis_count', 'Most Analyses'), ('analysis_count', 'Least Analyses')], default=0),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='allowed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='analysis_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='prerequisite_dics_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='rendition_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='renditions',
            field=models.ManyToManyField(default=None, to='Bable.Rendition'),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='sentence_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='votes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
    ]
