# Generated by Django 3.2.11 on 2023-01-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0004_alter_anon_post_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='votes_uniques',
            field=models.IntegerField(default=0),
        ),
    ]
