# Generated by Django 4.2.6 on 2023-10-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0004_searchurl_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchurl',
            name='has_voted',
            field=models.ManyToManyField(default=None, related_name='search_has_voted', to='Bable.author'),
        ),
        migrations.AddField(
            model_name='searchurl',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
