# Generated by Django 3.2.20 on 2023-08-09 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0004_auto_20230809_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page_density',
            old_name='ids',
            new_name='post_ids',
        ),
    ]
