# Generated by Django 3.2.24 on 2024-06-17 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0004_auto_20240617_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storefront',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', max_length=144)),
                ('preview_text', models.TextField(default='', max_length=1440)),
                ('disclaimer', models.TextField(default='', max_length=1440)),
                ('image_1', models.URLField(default='', max_length=2000)),
                ('image_2', models.URLField(default='', max_length=2000)),
                ('image_3', models.URLField(default='', max_length=2000)),
                ('image_4', models.URLField(default='', max_length=2000)),
                ('image_5', models.URLField(default='', max_length=2000)),
                ('template_section_size_1_1', models.IntegerField(default=0)),
                ('template_section_size_1_2', models.IntegerField(default=0)),
                ('template_section_size_1_3', models.IntegerField(default=0)),
                ('template_section_size_2_1', models.IntegerField(default=0)),
                ('template_section_size_2_2', models.IntegerField(default=0)),
                ('template_section_size_2_3', models.IntegerField(default=0)),
                ('template_section_size_3_1', models.IntegerField(default=0)),
                ('template_section_size_3_2', models.IntegerField(default=0)),
                ('template_section_size_3_3', models.IntegerField(default=0)),
                ('textblock_1', models.TextField(default='', max_length=14400)),
                ('textblock_2', models.TextField(default='', max_length=14400)),
                ('textblock_3', models.TextField(default='', max_length=14400)),
                ('textblock_4', models.TextField(default='', max_length=14400)),
                ('author', models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='Bable.author')),
                ('business_admin', models.ManyToManyField(default=None, related_name='business_admin', to='Bable.Author')),
                ('logo', models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='Bable.word')),
                ('products', models.ManyToManyField(default=None, to='Bable.Price')),
                ('sales', models.ManyToManyField(default=None, to='Bable.Sale')),
            ],
        ),
        migrations.AddField(
            model_name='anon',
            name='storefronts',
            field=models.ManyToManyField(default=None, to='Bable.Storefront'),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='storefronts',
            field=models.ManyToManyField(default=None, to='Bable.Storefront'),
        ),
        migrations.AddField(
            model_name='space',
            name='storefronts',
            field=models.ManyToManyField(default=None, to='Bable.Storefront'),
        ),
    ]
