# Generated by Django 4.1.5 on 2023-06-17 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0005_alter_votes_source_the_vote_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='the_vote_style',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='votename', to='Bable.spacesource'),
        ),
    ]
