# Generated by Django 3.2.11 on 2023-01-09 04:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0005_post_votes_uniques'),
    ]

    operations = [
        migrations.AddField(
            model_name='anon',
            name='anon_sort_char',
            field=models.CharField(choices=[('-sum_dictionaries', 'Most Dictionaries'), ('sum_dictionaries', 'Least Dictionaries'), ('-sum_purchased_dictionaries', 'Most Purchased Dictionaries'), ('sum_purchased_dictionaries', 'Least Purchased Dictionaries'), ('-sum_excluded_authors', 'Most Authors Blocked'), ('sum_excluded_authors', 'Least Authors Blocked'), ('-sum_examples', 'Most Examples'), ('sum_examlpes', 'Least Examples'), ('-sum_tasks', 'Most Tasks'), ('sum_tasks', 'Least Tasks'), ('-sum_posted_comments', 'Most Posted Comments'), ('sum_posted_comments', 'Least Posted Comments'), ('-sum_saved_comments', 'Most Saved Comments'), ('sum_saved_comments', 'Least Saved Comments'), ('-sum_purchased_spaces', 'Most Purchased Spaces'), ('sum_purchased_spaces', 'Least Purchased Spaces'), ('-sum_created_votestyles', 'Most Created Votestyles'), ('sum_created_votestyles', 'Least Created Votestyles'), ('-latest_change_date', 'Most Recent Update'), ('latest_change_date', 'Least Recent Update'), ('-creation_date', 'Newest Account Creation'), ('creation_date', 'Oldest Account Creation')], default='latest_change_date', max_length=180),
        ),
        migrations.AddField(
            model_name='anon',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='anon',
            name='past_votes',
            field=models.ManyToManyField(default=None, related_name='past_votes', to='Bable.Votes'),
        ),
        migrations.AddField(
            model_name='anon',
            name='sum_created_votestyles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='anon',
            name='sum_dictionaries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='anon',
            name='sum_examples',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='anon',
            name='sum_excluded_authors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='anon',
            name='sum_past_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='anon',
            name='sum_posted_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='anon',
            name='sum_posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='anon',
            name='sum_purchased_dictionaries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='anon',
            name='sum_purchased_spaces',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='anon',
            name='sum_saved_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='anon',
            name='sum_spaces',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='anon',
            name='sum_tasks',
            field=models.IntegerField(default=0),
        ),
    ]
