# Generated by Django 3.2.20 on 2023-08-13 04:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0005_rename_ids_page_density_post_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='Searches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_search_itself', models.CharField(default='', max_length=200)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='price',
            name='monthly',
            field=models.BooleanField(default=False),
        ),
    ]
