# Generated by Django 3.2.24 on 2024-03-29 20:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0005_searchurl_has_voted_searchurl_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Chapter X', max_length=220)),
                ('verses', models.TextField(default='In the beginning', max_length=14400)),
                ('side_notes', models.TextField(default='About this text', max_length=144000)),
                ('external_commentary', models.TextField(default="You've heard about this text", max_length=144000)),
                ('execution_prose', models.TextField(default='You hear this text better when we say', max_length=144000)),
                ('judiciary_feedback', models.TextField(default='You said this last time', max_length=144000)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliver_to_address', models.CharField(default='Digital Product', max_length=200)),
                ('deliver_to_instructions', models.CharField(default='Leave By Postbox', max_length=1440)),
                ('courier_order', models.CharField(default='', max_length=1440)),
                ('courier_fees', models.CharField(default='1', max_length=1440)),
                ('courier_1_to_2_drop_location', models.CharField(default='', max_length=1440)),
                ('courier_2_to_3_drop_location', models.CharField(default='', max_length=1440)),
                ('courier_3_to_4_drop_location', models.CharField(default='', max_length=1440)),
                ('courier_4_to_5_drop_location', models.CharField(default='', max_length=1440)),
                ('courier_5_to_6_drop_location', models.CharField(default='', max_length=1440)),
                ('courier_6_to_7_drop_location', models.CharField(default='', max_length=1440)),
                ('courier_1_to_2_drop_eta', models.CharField(default='', max_length=1440)),
                ('courier_1_to_2_drop_update', models.CharField(default='', max_length=1440)),
                ('courier_2_to_3_drop_eta', models.CharField(default='', max_length=1440)),
                ('courier_2_to_3_drop_update', models.CharField(default='', max_length=1440)),
                ('courier_3_to_4_drop_eta', models.CharField(default='', max_length=1440)),
                ('courier_3_to_4_drop_update', models.CharField(default='', max_length=1440)),
                ('courier_4_to_5_drop_eta', models.CharField(default='', max_length=1440)),
                ('courier_4_to_5_drop_update', models.CharField(default='', max_length=1440)),
                ('courier_5_to_6_drop_eta', models.CharField(default='', max_length=1440)),
                ('courier_5_to_6_drop_update', models.CharField(default='', max_length=1440)),
                ('courier_6_to_7_drop_eta', models.CharField(default='', max_length=1440)),
                ('courier_6_to_7_drop_update', models.CharField(default='', max_length=1440)),
                ('courier_select', models.ManyToManyField(default=None, related_name='courier_select', to='Bable.Author')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='Bable.author')),
            ],
        ),
        migrations.AddField(
            model_name='anon',
            name='student_of',
            field=models.ManyToManyField(default=None, related_name='student_of', to='Bable.Author'),
        ),
        migrations.AddField(
            model_name='anon',
            name='students',
            field=models.ManyToManyField(default=None, related_name='students', to='Bable.Author'),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='dictionary_wallet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='price',
            name='location_of_product',
            field=models.CharField(default='Remote', max_length=200),
        ),
        migrations.AddField(
            model_name='price',
            name='product_type',
            field=models.CharField(choices=[('unspecified', 'Unspecified'), ('package_post', 'Posted Package'), ('package_courier', 'Courier Routes Package'), ('package_direct', 'Choose A Courier'), ('package_pick_up', 'Pick Up Yourself (with a pick-up)'), ('package_collect', 'Collect Yourself (by hand)'), ('link', 'Collect Links'), ('poem', 'Just Words'), ('tickets', 'Event Tickets'), ('other', 'Other Deal')], default='unspecified', max_length=200),
        ),
        migrations.AddField(
            model_name='space',
            name='administrative_members',
            field=models.ManyToManyField(default=None, related_name='administrative_members', to='Bable.Author'),
        ),
        migrations.AddField(
            model_name='space',
            name='elected_admnisitrative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='space',
            name='elected_executive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='space',
            name='elected_judiciary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='space',
            name='elected_legislative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='space',
            name='executive_members',
            field=models.ManyToManyField(default=None, related_name='executive_members', to='Bable.Author'),
        ),
        migrations.AddField(
            model_name='space',
            name='judiciary_members',
            field=models.ManyToManyField(default=None, related_name='judiciary_members', to='Bable.Author'),
        ),
        migrations.AddField(
            model_name='space',
            name='legislative_members',
            field=models.ManyToManyField(default=None, related_name='legislative_members', to='Bable.Author'),
        ),
        migrations.AddField(
            model_name='space',
            name='space_wallet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='dictionary_source',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='Bable.dictionary_source'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='space_source',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='Bable.spacesource'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='word_source',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='Bable.word_source'),
        ),
        migrations.AddField(
            model_name='word',
            name='word_wallet',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Word_Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_total', models.IntegerField(default=0)),
                ('amount_owing', models.IntegerField(default=0)),
                ('repayment_term', models.DateTimeField(default=django.utils.timezone.now)),
                ('pro_rata', models.FloatField(default=0.08)),
                ('repayment_rates', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='hourly', max_length=144)),
                ('total_repayments_remaining', models.IntegerField(default=1)),
                ('total_repayments', models.IntegerField(default=1)),
                ('words', models.ManyToManyField(default=None, to='Bable.Word')),
            ],
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditions', models.TextField(default='Pay Attention 3000 Pounds of Flesh', max_length=1666000)),
                ('accostings', models.TextField(default="You've been accounted for as for the following", max_length=6660000)),
                ('primation_fee', models.IntegerField(default=1000)),
                ('conditionees', models.ManyToManyField(default=None, related_name='conditionees', to='Bable.Author')),
                ('conditioners', models.ManyToManyField(default=None, related_name='conditioners', to='Bable.Author')),
                ('primation_reference', models.ManyToManyField(default=None, related_name='reference', to='Bable.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Storefront',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disclaimer', models.TextField(default='', max_length=1440)),
                ('image_1', models.URLField(default='', max_length=2000)),
                ('image_2', models.URLField(default='', max_length=2000)),
                ('image_3', models.URLField(default='', max_length=2000)),
                ('image_4', models.URLField(default='', max_length=2000)),
                ('image_5', models.URLField(default='', max_length=2000)),
                ('textblock_1', models.TextField(default='', max_length=14400)),
                ('textblock_2', models.TextField(default='', max_length=14400)),
                ('textblock_3', models.TextField(default='', max_length=14400)),
                ('textblock_4', models.TextField(default='', max_length=14400)),
                ('business_admin', models.ManyToManyField(default=None, to='Bable.Author')),
                ('logo', models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='Bable.word')),
                ('products', models.ManyToManyField(default=None, to='Bable.Price')),
                ('sales', models.ManyToManyField(default=None, to='Bable.Sale')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_total', models.IntegerField(default=0)),
                ('amount_owing', models.IntegerField(default=0)),
                ('repayment_term', models.DateTimeField(default=django.utils.timezone.now)),
                ('pro_rata', models.FloatField(default=0.08)),
                ('repayment_rates', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='hourly', max_length=144)),
                ('total_repayments_remaining', models.IntegerField(default=1)),
                ('total_repayments', models.IntegerField(default=1)),
                ('spaces', models.ManyToManyField(default=None, to='Bable.Space')),
            ],
        ),
        migrations.CreateModel(
            name='Dictionary_Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_total', models.IntegerField(default=0)),
                ('amount_owing', models.IntegerField(default=0)),
                ('repayment_term', models.DateTimeField(default=django.utils.timezone.now)),
                ('pro_rata', models.FloatField(default=0.08)),
                ('repayment_rates', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='Hourly', max_length=144)),
                ('total_repayments_remaining', models.IntegerField(default=1)),
                ('total_repayments', models.IntegerField(default=1)),
                ('dictionaries', models.ManyToManyField(default=None, to='Bable.Dictionary')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concerning', models.TextField(default='All', max_length=140)),
                ('location', models.TextField(default='Zoom/Meets/Messenger/WhatsApp/Instagram/Discord', max_length=140)),
                ('start_time', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('available', models.BooleanField(default=False)),
                ('words', models.ManyToManyField(default=None, to='Bable.Word')),
            ],
        ),
        migrations.AddField(
            model_name='anon',
            name='availabilities',
            field=models.ManyToManyField(default=None, to='Bable.Availability'),
        ),
        migrations.AddField(
            model_name='anon',
            name='loans',
            field=models.ManyToManyField(default=None, to='Bable.Loan'),
        ),
        migrations.AddField(
            model_name='anon',
            name='storefronts',
            field=models.ManyToManyField(default=None, to='Bable.Storefront'),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='word_loans',
            field=models.ManyToManyField(default=None, to='Bable.Word_Loan'),
        ),
        migrations.AddField(
            model_name='price',
            name='point_of_sale',
            field=models.ManyToManyField(default=None, to='Bable.Sale'),
        ),
        migrations.AddField(
            model_name='space',
            name='adjudicating_terms',
            field=models.ManyToManyField(default=None, related_name='adjudicating', to='Bable.Terms'),
        ),
        migrations.AddField(
            model_name='space',
            name='adjudication',
            field=models.ManyToManyField(default=None, related_name='adjudication', to='Bable.Chapters'),
        ),
        migrations.AddField(
            model_name='space',
            name='administrating_terms',
            field=models.ManyToManyField(default=None, related_name='administrating', to='Bable.Terms'),
        ),
        migrations.AddField(
            model_name='space',
            name='administration',
            field=models.ManyToManyField(default=None, related_name='administration', to='Bable.Chapters'),
        ),
        migrations.AddField(
            model_name='space',
            name='dictionary_loans',
            field=models.ManyToManyField(default=None, to='Bable.Dictionary_Loan'),
        ),
        migrations.AddField(
            model_name='space',
            name='executing_terms',
            field=models.ManyToManyField(default=None, related_name='executing', to='Bable.Terms'),
        ),
        migrations.AddField(
            model_name='space',
            name='execution',
            field=models.ManyToManyField(default=None, related_name='execution', to='Bable.Chapters'),
        ),
        migrations.AddField(
            model_name='space',
            name='legislating_terms',
            field=models.ManyToManyField(default=None, related_name='legislating', to='Bable.Terms'),
        ),
        migrations.AddField(
            model_name='space',
            name='legislation',
            field=models.ManyToManyField(default=None, related_name='legislation', to='Bable.Chapters'),
        ),
    ]
