# Generated by Django 4.1.5 on 2023-03-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0006_auto_20230109_0421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Densitivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dense', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Page_Density',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='', max_length=15)),
                ('time_spent', models.IntegerField(default=0)),
                ('scroll_height', models.IntegerField(default=0)),
                ('client_height', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=2)),
                ('density', models.ManyToManyField(default=None, to='Bable.densitivity')),
            ],
        ),
        migrations.AddField(
            model_name='anon',
            name='home_page_density',
            field=models.ManyToManyField(default=None, to='Bable.page_density'),
        ),
    ]
