# Generated by Django 3.2.24 on 2024-03-29 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0006_auto_20240330_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='dictionary_source',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='space_source',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='word_source',
        ),
    ]
