# Generated by Django 3.2.20 on 2023-07-16 08:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0006_alter_anon_dictionary_sort_char'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='anon',
            name='attribute_sort_char',
            field=models.CharField(choices=[(0, 'latest'), (1, 'definitions'), (2, 'votes'), (3, '-votes'), (4, 'views'), (5, '-views')], default='the_attribute_itself', max_length=180),
        ),
        migrations.AddField(
            model_name='anon',
            name='word_sort_char',
            field=models.CharField(choices=[('the_word_itself', 'Alphabetical'), ('-the_word_itself', 'Anti Alphabetical'), ('-latest_change_date', 'Most Recent Change'), ('latest_change_date', 'Least Recent Change'), ('-creation_date', 'Most Recently Created'), ('creation_date', 'Least Recently Created'), ('-pronunciation_count', 'Most Pronunciations'), ('pronunciation_count', 'Least Pronunciations'), ('-attribute_count', 'Most Attributes'), ('attribute_count', 'Least Attributes'), ('-similarity_count', 'Most Similarities'), ('similarity_count', 'Least Similarities'), ('-translation_count', 'Most Translations'), ('translation_count', 'Least Translations'), ('-example_count', 'Most Examples'), ('example_count', 'Least Examples'), ('-relation_count', 'Most Relations'), ('relation_count', 'Least Relations'), ('-sponsor_count', 'Most Sponsors'), ('sponsor_count', 'Least Sponsors'), ('-viewcount', 'Most Viewed'), ('viewcount', 'Least Viewed'), ('-price_limit', 'Most Expensive'), ('price_limit', 'Least Expensive'), ('-space_count', 'Most Spaces'), ('space_count', 'Least Spaces'), ('-story_count', 'Most Stories'), ('story_count', 'Least Stories'), ('-vote_count', 'Most Votes'), ('vote_count', 'Least Votes')], default='viewcount', max_length=180),
        ),
        migrations.AddField(
            model_name='attribute',
            name='antonym_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attribute',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='attribute',
            name='definition_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attribute',
            name='homonym_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attribute',
            name='synonym_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rendition',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sentence',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='true_translation',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='votes',
            name='voters_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='ap_voter_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='attribute_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='example_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='pronunciation_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='relation_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='similarity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='space_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='sponsor_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='story_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='translation_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
