# Generated by Django 3.2.24 on 2024-03-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0007_auto_20240330_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anon',
            name='comment_sort_char',
            field=models.CharField(choices=[('sum_dictionaries', 'Generalist'), ('-sum_dictionaries', 'Broadness'), ('sum_words', 'Less Complex'), ('-sum_words', 'More Intelligent'), ('sum_sponsors', 'Encouraged'), ('-sum_sponsors', 'Discouraged'), ('votes_uniques', 'Less Uniques'), ('-votes_uniques', 'More Uniques'), ('-viewcount', 'Viewcount'), ('viewcount', 'Unseen'), ('-latest_change_date', 'Latest'), ('latest_change_date', 'Unchanged'), ('-sum_has_commented', 'Discussed'), ('sum_has_commented', 'Unspoken')], default='latest_change_date', max_length=180),
        ),
    ]
