# Generated by Django 4.1.5 on 2023-03-29 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0008_rename_url_advertising_url2_rename_url_file_url2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anon',
            name='post_sort_char',
            field=models.CharField(choices=[('-viewcount', 'Viral'), ('viewcount', 'Early'), ('-latest_change_date', 'Freshest'), ('latest_change_date', 'Eldest'), ('-sum_has_viewed', 'Uniques'), ('-sum_has_voted', 'Voters'), ('-sum_dictionaries', 'Broadness'), ('-sum_words', 'Intricacy'), ('-sum_comments', 'Talkative'), ('sum_comments', 'Silencio'), ('-under_talked', 'Under Commented'), ('under_talked', 'Over Commented'), ('-sum_spaces', 'Homes'), ('-sum_sponsors', 'Encouraged'), ('-votes_count', 'Votes'), ('votes_count', 'Unvoted')], default='latest_change_date', max_length=180),
        ),
        migrations.AddField(
            model_name='post',
            name='under_talked',
            field=models.FloatField(default=0),
        ),
    ]
