# Generated by Django 3.2.24 on 2024-04-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0008_alter_anon_comment_sort_char'),
    ]

    operations = [
        migrations.AddField(
            model_name='anon',
            name='employed_by',
            field=models.ManyToManyField(default=None, related_name='employed_by', to='Bable.Author'),
        ),
        migrations.AddField(
            model_name='anon',
            name='employees',
            field=models.ManyToManyField(default=None, related_name='employees', to='Bable.Author'),
        ),
        migrations.AddField(
            model_name='anon',
            name='shared_with_availabilities',
            field=models.ManyToManyField(default=None, related_name='shared_with_availabilities', to='Bable.Availability'),
        ),
        migrations.AlterField(
            model_name='anon',
            name='availabilities',
            field=models.ManyToManyField(default=None, related_name='availabilities', to='Bable.Availability'),
        ),
        migrations.AlterField(
            model_name='price',
            name='product_type',
            field=models.CharField(choices=[('unspecified', 'Unspecified'), ('package_post', 'Posted Package'), ('package_courier', 'Courier Routes Package'), ('package_direct', 'Choose A Courier'), ('package_pick_up', 'Pick Up Yourself (with a pick-up)'), ('package_collect', 'Collect Yourself (by hand)'), ('link', 'Collect Links'), ('poem', 'Just Words'), ('tickets', 'Event Tickets'), ('classes', 'Classes'), ('class_material', 'Class Material'), ('other', 'Other Deal')], default='unspecified', max_length=200),
        ),
    ]
