# Generated by Django 3.2.20 on 2023-07-18 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0008_alter_anon_dictionary_sort_char'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stripe_product_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='dictionary',
            name='dictionary_source',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='dictionary_source',
            name='dictionary_id',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='post',
            name='post_source',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='word',
            name='word_source',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='word_source',
            name='word_id',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_price_id', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bable.product')),
            ],
        ),
        migrations.AddField(
            model_name='edit',
            name='post_source',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Bable.postsource'),
        ),
        migrations.AddField(
            model_name='post',
            name='products',
            field=models.ManyToManyField(default=None, to='Bable.Price'),
        ),
    ]
