# Generated by Django 4.1.5 on 2023-03-30 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0009_anon_post_sort_char_post_under_talked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='sum_sum_has_viewed',
            new_name='sum_has_viewed',
        ),
        migrations.AddField(
            model_name='anon',
            name='comment_sort_char',
            field=models.CharField(choices=[('sum_dctionaries', 'Generalist'), ('-sum_dictionaries', 'Broadness'), ('sum_words', 'Less Complex'), ('-sum_words', 'More Intelligent'), ('sum_sponsors', 'Encouraged'), ('-sum_sponsors', 'Discouraged'), ('sum_has_voted', 'Less Uniques'), ('-sum_has_voted', 'More Uniques'), ('-viewcount', 'Viewcount'), ('viewcount', 'Unseen'), ('-latest_change_date', 'Latest'), ('latest_change_date', 'Unchanged'), ('-sum_has_commented', 'Discussed'), ('sum_has_commented', 'Unspoken')], default='latest_change_date', max_length=180),
        ),
    ]
