# Generated by Django 3.2.20 on 2023-07-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0009_auto_20230718_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='product',
        ),
        migrations.AddField(
            model_name='price',
            name='stripe_product_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='price',
            name='stripe_price_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
