# Generated by Django 3.2.24 on 2024-04-13 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0009_auto_20240402_0506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='space',
            old_name='elected_admnisitrative',
            new_name='elected_administrative',
        ),
        migrations.AddField(
            model_name='terms',
            name='chapter',
            field=models.CharField(default='', max_length=160),
        ),
        migrations.AddField(
            model_name='terms',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
