# Generated by Django 4.1.5 on 2023-04-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0010_rename_sum_sum_has_viewed_comment_sum_has_viewed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='fontsize',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='word',
            name='fontstyle',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='word',
            name='fontype',
            field=models.TextField(default='', max_length=14400),
        ),
    ]
