# Generated by Django 3.2.20 on 2023-07-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0010_auto_20230718_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='anon',
            name='stripe_private_key',
            field=models.CharField(default='', max_length=600),
        ),
    ]
