# Generated by Django 3.2.24 on 2024-04-18 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0010_auto_20240413_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberVotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('legislative', 'Legislative'), ('administrative', 'Administrative'), ('executive', 'Executive'), ('judiciary', 'Judiciary')], default='legislative', max_length=144)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bable.spacesource')),
                ('vote_member', models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='vote_member', to='Bable.author')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter', to='Bable.author')),
            ],
        ),
        migrations.AddField(
            model_name='space',
            name='administrative_votes',
            field=models.ManyToManyField(default=None, related_name='administrative_votes', to='Bable.MemberVotes'),
        ),
        migrations.AddField(
            model_name='space',
            name='executive_votes',
            field=models.ManyToManyField(default=None, related_name='executive_votes', to='Bable.MemberVotes'),
        ),
        migrations.AddField(
            model_name='space',
            name='judiciary_votes',
            field=models.ManyToManyField(default=None, related_name='judiciary_votes', to='Bable.MemberVotes'),
        ),
        migrations.AddField(
            model_name='space',
            name='legislative_votes',
            field=models.ManyToManyField(default=None, related_name='legislative_votes', to='Bable.MemberVotes'),
        ),
    ]
