# Generated by Django 4.1.5 on 2023-06-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0011_word_fontsize_word_fontstyle_word_fontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sum_has_voted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='anon',
            name='comment_sort_char',
            field=models.CharField(choices=[('sum_dctionaries', 'Generalist'), ('-sum_dictionaries', 'Broadness'), ('sum_words', 'Less Complex'), ('-sum_words', 'More Intelligent'), ('sum_sponsors', 'Encouraged'), ('-sum_sponsors', 'Discouraged'), ('votes_uniques', 'Less Uniques'), ('-votes_uniques', 'More Uniques'), ('-viewcount', 'Viewcount'), ('viewcount', 'Unseen'), ('-latest_change_date', 'Latest'), ('latest_change_date', 'Unchanged'), ('-sum_has_commented', 'Discussed'), ('sum_has_commented', 'Unspoken')], default='latest_change_date', max_length=180),
        ),
    ]
