# Generated by Django 3.2.24 on 2024-05-13 05:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0011_auto_20240418_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='BezierCurveTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x1', models.IntegerField(default=0)),
                ('y1', models.IntegerField(default=0)),
                ('x2', models.IntegerField(default=0)),
                ('y2', models.IntegerField(default=0)),
                ('x3', models.IntegerField(default=0)),
                ('y3', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LineTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_width', models.FloatField(default=5.0)),
                ('stroke_style', models.TextField(default='black', max_length=2000)),
                ('stroke', models.BooleanField(default=False)),
                ('fill_style', models.TextField(default='black', max_length=2000)),
                ('fill', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('line_to', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Bable.lineto')),
            ],
        ),
        migrations.CreateModel(
            name='MoveTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='QuadraticCurveTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('p1', models.IntegerField(default=0)),
                ('p2', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rectangle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('paste', models.TextField(default='var x = 150;var y = 50;var width = 200;var height = 250;context.strokeRect(x, y, width, height);', max_length=150)),
                ('filled', models.BooleanField(default=False)),
                ('clear', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='space',
            name='mission',
            field=models.TextField(default='Mission', max_length=1000),
        ),
        migrations.AddField(
            model_name='space',
            name='values',
            field=models.TextField(default='Values', max_length=1000),
        ),
        migrations.AddField(
            model_name='space',
            name='vision',
            field=models.TextField(default='Vision', max_length=1000),
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movements', models.ManyToManyField(default=None, to='Bable.Movement')),
            ],
        ),
        migrations.AddField(
            model_name='movement',
            name='move_to',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Bable.moveto'),
        ),
        migrations.AddField(
            model_name='movement',
            name='quadratic_curve_to',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Bable.quadraticcurveto'),
        ),
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Builder Owners Project', max_length=140)),
                ('created_date', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('latest_change_date', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('init', models.TextField(default="<script>function rectangle() {var canvas = document.getElementById('canvas');var context = canvas.getContext('2d');}</script>", max_length=20000)),
                ('author', models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='Bable.author')),
                ('rectangles', models.ManyToManyField(default=None, to='Bable.Rectangle')),
            ],
        ),
        migrations.AddField(
            model_name='anon',
            name='drawings',
            field=models.ManyToManyField(default=None, to='Bable.Drawing'),
        ),
    ]
