# Generated by Django 3.2.24 on 2024-05-19 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0012_auto_20240513_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArcTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('radius', models.IntegerField(default=0)),
                ('start_angle', models.IntegerField(default=0)),
                ('end_angle', models.IntegerField(default=0)),
                ('counter_clockwise', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='space',
            name='administrative_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='space',
            name='executive_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='space',
            name='judiciary_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='space',
            name='legislative_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='space',
            name='progressive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='space',
            name='successive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movement',
            name='arc_to',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Bable.arcto'),
        ),
    ]
