# Generated by Django 4.1.5 on 2023-06-17 03:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0012_post_sum_has_voted_alter_anon_comment_sort_char'),
    ]

    operations = [
        migrations.AddField(
            model_name='votes',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='votes',
            name='the_vote_name',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
