# Generated by Django 3.2.20 on 2023-07-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0012_auto_20230718_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='anon',
            name='stripe_api_secret',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='price',
            name='img',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='price',
            name='url2',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
    ]
