# Generated by Django 3.2.20 on 2023-07-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0013_auto_20230718_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='anon',
            name='purchases',
            field=models.ManyToManyField(default=None, related_name='anon_purchase', to='Bable.Price'),
        ),
        migrations.AlterField(
            model_name='anon',
            name='products',
            field=models.ManyToManyField(default=None, related_name='anon_product', to='Bable.Price'),
        ),
    ]
