# Generated by Django 3.2.24 on 2024-05-21 00:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0013_auto_20240519_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='administrative_blind',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='space',
            name='administrative_conditionees_select_primate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='space',
            name='administrative_conditioners_select_external',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='space',
            name='executive_blind',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='space',
            name='executive_conditionees_select_primate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='space',
            name='executive_conditioners_select_external',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='space',
            name='judiciary_blind',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='space',
            name='judiciary_conditionees_select_primate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='space',
            name='judiciary_conditioners_select_external',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='space',
            name='legislative_blind',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='space',
            name='legislative_conditionees_select_primate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='space',
            name='legislative_conditioners_select_external',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='terms',
            name='conditionees_select_primate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='terms',
            name='conditioners_select_external',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_value', models.IntegerField(default=0)),
                ('barcode_meaning', models.TextField(default='', max_length=144)),
                ('barcode_definition', models.TextField(default='', max_length=1440)),
                ('barcode_story', models.TextField(default='', max_length=14400)),
                ('sum_has_commented', models.IntegerField(default=0)),
                ('sum_has_viewed', models.IntegerField(default=0)),
                ('sum_has_voted', models.IntegerField(default=0)),
                ('votes_uniques', models.IntegerField(default=0)),
                ('sum_comments', models.IntegerField(default=0)),
                ('sum_sponsors', models.IntegerField(default=0)),
                ('viewcount', models.IntegerField(default=0)),
                ('change_count', models.IntegerField(default=0)),
                ('latest_change_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comments', models.ManyToManyField(default=None, to='Bable.Comment')),
                ('has_commented', models.ManyToManyField(default=None, related_name='barcode_has_commented', to='Bable.Author')),
                ('has_viewed', models.ManyToManyField(default=None, related_name='barcode_has_viewed', to='Bable.Author')),
                ('has_voted', models.ManyToManyField(default=None, related_name='barcode_has_voted', to='Bable.Author')),
                ('sponsors', models.ManyToManyField(default=None, to='Bable.Sponsor')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='barcodes',
            field=models.ManyToManyField(default=None, to='Bable.Barcode'),
        ),
    ]
