# Generated by Django 3.2.24 on 2024-05-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0014_auto_20240521_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='children_count',
            field=models.IntegerField(default=0),
        ),
    ]
