# Generated by Django 3.2.20 on 2023-07-22 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0014_auto_20230718_2331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='url2',
            new_name='url2purchase',
        ),
        migrations.AddField(
            model_name='price',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='Bable.author'),
        ),
        migrations.AddField(
            model_name='price',
            name='description2helpsell',
            field=models.TextField(default='', max_length=144000),
        ),
        migrations.AddField(
            model_name='price',
            name='description2purchase',
            field=models.TextField(default='', max_length=144000),
        ),
        migrations.AlterField(
            model_name='edit',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='Bable.author'),
        ),
        migrations.AlterField(
            model_name='edit',
            name='post_source',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='Bable.postsource'),
        ),
    ]
