# Generated by Django 3.2.24 on 2024-05-25 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0015_comment_children_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('r', models.IntegerField(default=0)),
                ('n', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Triangle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.IntegerField(default=0)),
                ('b', models.IntegerField(default=0)),
                ('c', models.IntegerField(default=0)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('theta', models.FloatField(default=0)),
                ('fill_style', models.CharField(default='blue', max_length=14)),
            ],
        ),
        migrations.AddField(
            model_name='anon',
            name='saless',
            field=models.ManyToManyField(default=None, to='Bable.Sale'),
        ),
        migrations.AddField(
            model_name='post',
            name='sales',
            field=models.ManyToManyField(default=None, to='Bable.Sale'),
        ),
        migrations.AddField(
            model_name='sale',
            name='price_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='storefront',
            name='author',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='Bable.author'),
        ),
        migrations.AddField(
            model_name='storefront',
            name='preview_text',
            field=models.TextField(default='', max_length=1440),
        ),
        migrations.AddField(
            model_name='storefront',
            name='template_section_size_1_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storefront',
            name='template_section_size_1_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storefront',
            name='template_section_size_1_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storefront',
            name='template_section_size_2_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storefront',
            name='template_section_size_2_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storefront',
            name='template_section_size_2_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storefront',
            name='template_section_size_3_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storefront',
            name='template_section_size_3_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storefront',
            name='template_section_size_3_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storefront',
            name='title',
            field=models.TextField(default='', max_length=144),
        ),
        migrations.AlterField(
            model_name='storefront',
            name='business_admin',
            field=models.ManyToManyField(default=None, related_name='business_admin', to='Bable.Author'),
        ),
        migrations.CreateModel(
            name='ConditionEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditions', models.TextField(default='Pay Attention 3000 Pounds of Flesh', max_length=1666000)),
                ('votes', models.ManyToManyField(default=None, to='Bable.Author')),
            ],
        ),
        migrations.CreateModel(
            name='ConditionalVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votee', models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='conditional_votee', to='Bable.author')),
                ('votes', models.ManyToManyField(default=None, related_name='conditional_votes', to='Bable.Author')),
            ],
        ),
        migrations.AddField(
            model_name='terms',
            name='condition_edits',
            field=models.ManyToManyField(default=None, to='Bable.ConditionEdit'),
        ),
        migrations.AddField(
            model_name='terms',
            name='conditionee_votes',
            field=models.ManyToManyField(default=None, related_name='conditionee_votes', to='Bable.ConditionalVote'),
        ),
        migrations.AddField(
            model_name='terms',
            name='conditioner_votes',
            field=models.ManyToManyField(default=None, related_name='conditioner_votes', to='Bable.ConditionalVote'),
        ),
    ]
