# Generated by Django 3.2.24 on 2024-06-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bable', '0020_dictionary_storefronts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='comments',
        ),
        migrations.AddField(
            model_name='space',
            name='storefronts',
            field=models.ManyToManyField(default=None, to='Bable.Storefront'),
        ),
    ]
